### ISSUE TITLE
Import not working

### ISSUE THREAD

**Issue by jbehuet** [NextFaze/angular-rollbar#3]
```
import { RollbarModule } from 'angular-rollbar';
import { RollbarService } from  'angular-rollbar';
```

You need to use : 

```
import { RollbarModule } from 'angular-rollbar/lib';
import { RollbarService } from  'angular-rollbar/lib';
```

**Comment by MichaelMarner** [comment]
Thanks for reporting this issue. I've pushed a fix (simple change to package.json) that should fix finding the typings files.

You can now import like so:

    import { RollbarModule, RollbarService } from 'angular-rollbar';

This fix is in `0.0.2` on npm
